Feature/layout popup bio
adrianponce89/octosoft pull request #45
Opened 2021-02-06 02:24 UTC by DIOLINK

![image](https://user-images.githubusercontent.com/54718297/107106168-0dc5e700-6809-11eb-8fde-494186cab8db.png)
![Peek 05-02-2021 23-23](https://user-images.githubusercontent.com/54718297/107106229-41a10c80-6809-11eb-8b28-c28a7fda6a26.gif)

2021-02-07 16:20 UTC, adrianponce89 requested changes
Muy bien, solo el tema de que la foto es otra variable mas, pero lo demás muy bien

2021-02-07 16:20 UTC, adrianponce89 commented on src/components/OurTeam/index.js
> +            background={`url(${selectedMember.node.photo.file.url})`}
```             background={`url(${selectedMember.node.full_photo.file.url})`}```
             Usa full_photo o parecido, la foto debe ser diferente de la foto miniatura usada ahora, son fotos de medio perfil, no solo de cara

2021-02-07 16:20 UTC, adrianponce89 commented on src/pages/aboutus.js
>            name
agrega full_photo o similar, para traer una foto diferente de la usada para la miniatura

2021-02-07 16:20 UTC, adrianponce89 commented on src/components/OurTeam/OurTeamModal.js
> +    clipPath:
Las imagenes que aparecen acá no deberian ser octogonales, remove todo el clippath

2021-02-07 16:22 UTC, adrianponce89 commented on src/components/OurTeam/OurTeamModal.js
> +      lineHeight: '1.5em',
Las letras mas grandes

2021-02-09 15:48 UTC, DIOLINK commented on src/components/OurTeam/index.js
> +            background={`url(${selectedMember.node.photo.file.url})`}
cargue las mismas fotos porque no tengo nuevas

2021-02-09 16:49 UTC, DIOLINK commented
![image](https://user-images.githubusercontent.com/54718297/107397498-764ce680-6add-11eb-974f-ad304871687f.png)
![image](https://user-images.githubusercontent.com/54718297/107397714-a98f7580-6add-11eb-9272-cd379453e5f4.png)

2021-02-09 17:15 UTC, adrianponce89 commented
Por favor agrega un padding o magin interno de al menos 1em entre los textos/imagen y el exterior del modal. Que el modal conserve cierta proporcion de altura maxima, en pantallas grandes toda la imagen se deforma, tambien al achicar la vista

2021-02-09 17:16 UTC, adrianponce89 requested changes
Por favor agrega un padding o magin interno de al menos 1em entre los textos/imagen y el exterior del modal. Que el modal conserve cierta proporcion de altura maxima, en pantallas grandes toda la imagen se deforma, tambien al achicar la vista

2021-02-11 14:49 UTC, DIOLINK commented
![image](https://user-images.githubusercontent.com/54718297/107652335-3c0b5280-6c5f-11eb-848c-64e8b13047f3.png)

2021-02-11 14:54 UTC, adrianponce89 commented
![image](https://user-images.githubusercontent.com/16446864/107652813-bf2ca880-6c5f-11eb-8a4f-4c89fd1e4a30.png)

2021-02-11 14:55 UTC, adrianponce89 commented
![image](https://user-images.githubusercontent.com/16446864/107653078-03b84400-6c60-11eb-9b45-750734ec3728.png)

2021-02-11 14:57 UTC, adrianponce89 commented
Agrega ademas un puntero para cuando se pasa por encima de las caras por favor. Si no, no hay manra de saber que son botones. Capas algún efecto de resaltado/sombreado tambien

2021-02-11 15:11 UTC, DIOLINK commented
![Peek 11-02-2021 12-08](https://user-images.githubusercontent.com/54718297/107655328-3bc08680-6c62-11eb-974e-40897e3b2841.gif)

2021-02-11 15:24 UTC, adrianponce89 requested changes
Por favor arregla la ruptura del contenido del pop-up cuando se achica la ventana del navegador manualmente, y tambien cuando la resolucion es muy alta (eso se puede probar cambiando el zoom)

![image](https://user-images.githubusercontent.com/16446864/107657313-d4a3d180-6c63-11eb-8b3e-ae644fdb6114.png)

2021-02-11 17:15 UTC, DIOLINK commented
![Peek 11-02-2021 14-14](https://user-images.githubusercontent.com/54718297/107672339-88f92400-6c73-11eb-9506-8aa1cc3fc48e.gif)

2021-02-11 18:57 UTC, adrianponce89 approved these changes

2021-02-11 19:00 UTC, merged