Feature/new home
adrianponce89/octosoft pull request #62
Opened 2021-07-17 04:26 UTC by agusruidiazgd

![Peek 2021-07-17 01-23](https://user-images.githubusercontent.com/61565784/126025342-69238fa5-af5f-4dad-a5cf-88ad5e96b19c.gif)
![Peek 2021-07-17 01-22](https://user-images.githubusercontent.com/61565784/126025380-5a32a1d7-a3da-4b44-8d45-af017c2dbb21.gif)

2021-07-17 04:30 UTC, agusruidiazgd commented
Plan Card: I used plan's text of contentful and I did not change de font size because the title should be shorter, dont you?

2021-08-03 14:22 UTC, adrianponce89 requested changes
Seguir el mock up:

 https://www.figma.com/proto/Na68lmx0cClXSUY2Wg0N0d/HomeRevamp?node-id=5%3A87&scaling=contain&page-id=0%3A1

2021-08-03 14:22 UTC, adrianponce89 commented on src/components/DescriptionHome.js
> +          </Typography>
Esta informacion deberia venir de contenful, agregar el campo si es necesario

2021-08-03 14:24 UTC, adrianponce89 commented
Centrar iconos:
![Screen Shot 2021-08-03 at 11 21 46](https://user-images.githubusercontent.com/16446864/128032273-a20eaea2-4294-4ec7-b560-baa4aae0b054.png)

Que el texto no se salga del recuadro (Si es necesario, quitar los centavos y achicar letra)
![Screen Shot 2021-08-03 at 11 21 40](https://user-images.githubusercontent.com/16446864/128032279-33c9d43b-6a0b-459b-ae62-cf1a0925a12e.png)

2021-08-03 14:27 UTC, adrianponce89 commented
Los iconos tienen que tener un octogono color azuloscuro como en el mockup:
![Screen Shot 2021-08-03 at 11 25 47](https://user-images.githubusercontent.com/16446864/128032781-5b690609-c7f6-4eb4-8f17-f69ba6ae0b6c.png)

2021-08-03 14:27 UTC, adrianponce89 commented on src/components/DescriptionHome.js
> +          </Typography>
Cambiar la informacion de contenful para reflejar
![Screen Shot 2021-08-03 at 11 25 58](https://user-images.githubusercontent.com/16446864/128032789-fe4c83f8-99ea-4644-8f83-ac9d11486711.png)

2021-08-03 14:34 UTC, adrianponce89 commented
Agregar la parte de Clients who trust us:

![Screen Shot 2021-08-03 at 11 32 44](https://user-images.githubusercontent.com/16446864/128033860-50e9106c-3636-4f92-ae00-d5ce2c5fed1f.png)


Esta informacion deberia venir de contenful y pero si esta vacia no se deberia mostrar. Cada client tiene un nombre, una imagen y un link. El nombre se usa como el Alt de la imagen, el link se usa para cuando se presiona en la imagen para enviar a la pagina web del cliente o algo asi

2021-09-05 16:13 UTC, agusruidiazgd commented
![OCTO](https://user-images.githubusercontent.com/61565784/132133727-0d14c096-6981-4821-aa2f-85711f92e534.gif)
![OCTOMOBILE](https://user-images.githubusercontent.com/61565784/132133733-9a18f067-9499-44ba-a575-40fb354cd931.gif)

2021-09-06 20:30 UTC, adrianponce89 commented
@agusruidiazgd ! Te dejo el feedback de diseńo:

Yas Gaya:
-----

En primera instancia: el efecto de la transición de color en el puente no está. El logo que aparece a continuación, creo que iba el que yo dibujé. Por otro lado, los 8 servicios, en versión compu se ven 3, 3 y 2 y no queda bien a mí parecer.
Ok, entonces:
REPASO:
Puente con transición de color
Logo ilustrado
Video Promo
Emprolijar orden de los 8 servicios para PC
Reducir mil iconitos en Our Clients
😆

![WhatsApp Image 2021-09-06 at 17 24 23](https://user-images.githubusercontent.com/16446864/132259013-966c5cab-2ed8-4926-b60a-5748832c7dfb.jpeg)

2021-09-06 20:31 UTC, adrianponce89 requested changes
Respecto al codigo esta bien pero solicitan algunos arreglos desde diseño. Respecto a la animacion podemos estimar unos puntos mas

2021-09-18 13:25 UTC, agusruidiazgd commented
![i](https://user-images.githubusercontent.com/61565784/133890437-4b20fa02-3eb2-4d2d-b411-c064e7202dfe.gif)

2022-02-03 15:34 UTC, merged