Aesthetic polish/about us
adrianponce89/octosoft pull request #63
Opened 2021-09-05 00:09 UTC by DIOLINK

![image](https://user-images.githubusercontent.com/54718297/132110862-86f5767c-ffaa-4195-981a-25472d676d0b.png)
![image](https://user-images.githubusercontent.com/54718297/132110866-52bac217-bc95-4903-9e31-182f2ccdde74.png)
![image](https://user-images.githubusercontent.com/54718297/132110867-2c6840f2-f3fd-4bb7-bbb6-4f12097cab67.png)
![image](https://user-images.githubusercontent.com/54718297/132110870-c81ca6bc-f1f3-4e66-a682-d6915da23cb8.png)

2021-09-05 12:46 UTC, agusruidiazgd approved these changes

2021-09-06 20:55 UTC, adrianponce89 commented
@DIOLINK cambios pedidos de diseño, aplicar como imagenes:


![WhatsApp Image 2021-09-06 at 17 51 08](https://user-images.githubusercontent.com/16446864/132260030-96c0218b-3dd7-4ece-a8b4-d1fc7de0c9b7.jpeg)



Esta pero con los octogonitos arriba en corners laterales en el txt de presentación
![WhatsApp Image 2021-09-06 at 17 48 58](https://user-images.githubusercontent.com/16446864/132260035-a1872f1c-6567-4286-be54-e0b15eb34a77.jpeg)

2021-09-06 20:55 UTC, adrianponce89 requested changes
Update with changes required by design

2021-09-14 19:51 UTC, DIOLINK commented
![image](https://user-images.githubusercontent.com/54718297/133320015-1f783036-b851-49c2-9b07-750964888199.png)
![Peek 14-09-2021 16-18](https://user-images.githubusercontent.com/54718297/133324382-db535e7a-5024-40c0-aa74-8bc0fba25b24.gif)

2021-09-14 20:05 UTC, merged